from enum import StrEnum
from typing import Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    NonNegativeFloat,
    NonNegativeInt,
    model_validator,
)


class QuestionType(StrEnum):
    """
    Supported evaluation question types.
    """

    FACTOID = "factoid"
    MULTI_HOP = "multi_hop"
    ABSTRACTIVE = "abstractive"
    ADVERSARIAL = "adversarial"
    COMPARATIVE = "comparative"
    UNANSWERABLE = "unanswerable"


class FailureMode(StrEnum):
    """
    Typed failure modes used during error analysis.
    """

    RETRIEVAL_MISS = "RETRIEVAL_MISS"
    RETRIEVAL_RANK = "RETRIEVAL_RANK"
    CONTEXT_IGNORED = "CONTEXT_IGNORED"
    HALLUCINATION = "HALLUCINATION"
    PARTIAL_ANSWER = "PARTIAL_ANSWER"
    UNANSWERABLE_FAIL = "UNANSWERABLE_FAIL"
    MULTI_HOP_INCOMPLETE = "MULTI_HOP_INCOMPLETE"
    COMPARISON_INCOMPLETE = "COMPARISON_INCOMPLETE"
    ABSTRACTIVE_UNGROUNDED = "ABSTRACTIVE_UNGROUNDED"
    ADVERSARIAL_MISREAD = "ADVERSARIAL_MISREAD"


class EvidenceSpan(BaseModel):
    """
    Character-level evidence span inside a source document or chunk.
    """

    model_config = ConfigDict(extra="forbid")

    document_id: str
    chunk_id: str | None = None
    start_char: NonNegativeInt
    end_char: NonNegativeInt
    text: str | None = None


class EvalSample(BaseModel):
    """
    Normalized evaluation sample shared by all datasets and synthetic generators.
    """

    model_config = ConfigDict(extra="forbid")

    sample_id: str
    question: str
    reference_answer: str | None = None
    answer_aliases: list[str] = Field(default_factory=list)
    choices: list[str] = Field(default_factory=list)
    question_type: QuestionType
    source_dataset: str
    source_split: str | None = None
    source_id: str | None = None
    evidence_chunk_ids: list[str] = Field(default_factory=list)
    evidence_spans: list[EvidenceSpan] = Field(default_factory=list)
    is_answerable: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)


class Chunk(BaseModel):
    """
    A chunk produced by an ingestion layer.
    """

    model_config = ConfigDict(extra="forbid")

    chunk_id: str
    document_id: str
    text: str
    start_char: NonNegativeInt | None = None
    end_char: NonNegativeInt | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class RetrievedChunk(BaseModel):
    """
    A retrieved chunk with rank and retrieval score.
    """

    model_config = ConfigDict(extra="forbid")

    chunk: Chunk
    rank: NonNegativeInt
    score: float
    retriever_name: str
    metadata: dict[str, Any] = Field(default_factory=dict)


class GeneratedAnswer(BaseModel):
    """
    Answer generated by a RAG pipeline for one evaluation sample.
    """

    model_config = ConfigDict(extra="forbid")

    sample_id: str
    answer: str
    model_name: str
    prompt_tokens: NonNegativeInt | None = None
    completion_tokens: NonNegativeInt | None = None
    latency_ms: NonNegativeInt | None = None
    cost_usd: NonNegativeFloat = 0.0
    metadata: dict[str, Any] = Field(default_factory=dict)


class FinalContext(BaseModel):
    """
    Final reranked context passed to the generator.
    """

    model_config = ConfigDict(extra="forbid")

    chunks: list[Chunk] = Field(default_factory=list)
    rendered_text: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)


class RetrievalMetrics(BaseModel):
    """
    Retrieval-only metrics for one sample or aggregate slice.
    """

    model_config = ConfigDict(extra="forbid")

    precision_at_k: float | None = None
    recall_at_k: float | None = None
    mrr: float | None = None
    ndcg: float | None = None


class GenerationMetrics(BaseModel):
    """
    Generation-only metrics for one sample or aggregate slice.
    """

    model_config = ConfigDict(extra="forbid")

    faithfulness: float | None = None
    relevance: float | None = None
    hallucination: float | None = None
    bert_score: float | None = None


class EvalResult(BaseModel):
    """
    Final scored result for one sample under one pipeline configuration.
    """

    model_config = ConfigDict(extra="forbid")

    run_id: str
    sample: EvalSample
    retrieved_chunks: list[RetrievedChunk]
    final_context: FinalContext = Field(default_factory=FinalContext)
    generated_answer: GeneratedAnswer | None = None
    retrieval_metrics: RetrievalMetrics
    generation_metrics: GenerationMetrics | None = None
    failure_modes: list[FailureMode] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="before")
    @classmethod
    def _coerce_legacy_final_context(cls, value: Any) -> Any:
        if not isinstance(value, dict):
            return value

        if "final_context" in value or "final_context_chunks" not in value:
            return value

        final_context = {
            "chunks": value.get("final_context_chunks") or [],
            "rendered_text": value.get("final_context_text") or "",
            "metadata": value.get("final_context_metadata") or {},
        }
        coerced = dict(value)
        coerced["final_context"] = final_context
        coerced.pop("final_context_chunks", None)
        coerced.pop("final_context_text", None)
        coerced.pop("final_context_metadata", None)
        return coerced

    @property
    def final_context_chunks(self) -> list[Chunk]:
        return self.final_context.chunks
